# Generated by Django 6.1.1 on 2026-09-16 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged in'), ('LOGOUT', 'Logged out'), ('EXPORT', 'Exported data'), ('BACKUP', 'Backed up data')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Customer ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('ghana_card', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Ghana Card / ID number')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('alt_phone', models.CharField(blank=True, max_length=30, verbose_name='Alternative phone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Residential address')),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('date_registered', models.DateField(default=django.utils.timezone.localdate)),
                ('next_of_kin', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Land ID')),
                ('plot_number', models.CharField(max_length=50, verbose_name='Plot number')),
                ('block_number', models.CharField(blank=True, max_length=50, verbose_name='Block number')),
                ('location', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, max_length=120)),
                ('land_size', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('size_unit', models.CharField(choices=[('ACRES', 'Acres'), ('HECTARES', 'Hectares'), ('PLOT', 'Plot(s)'), ('SQM', 'Square metres')], default='PLOT', max_length=20, verbose_name='Unit')),
                ('land_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('MIXED', 'Mixed Use'), ('OTHER', 'Other')], default='RESIDENTIAL', max_length=20, verbose_name='Land type')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=120, verbose_name='GPS / location information')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Transaction ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Initial payment method')),
                ('notes', models.TextField(blank=True, verbose_name='Transaction notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer')),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='core.land')),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment method')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Receipt number')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.sale')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('LAND', 'Land document'), ('AGREEMENT', 'Agreement'), ('RECEIPT', 'Receipt'), ('SITE_PLAN', 'Site plan'), ('IDENTIFICATION', 'Identification document'), ('ALLOCATION', 'Allocation document'), ('OTHER', 'Other supporting document')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.land')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.sale')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STAFF', 'Staff / Worker')], default='STAFF', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('can_delete', models.BooleanField(default=False, help_text='Allow this staff member to delete records.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='land',
            constraint=models.UniqueConstraint(fields=('plot_number', 'block_number'), name='unique_plot_per_block'),
        ),
    ]
