# Generated by Django 6.1.1 on 2026-09-16 21:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Record no.')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('buyer_name', models.CharField(max_length=150, verbose_name='Buyer / customer')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('id_number', models.CharField(blank=True, max_length=60, verbose_name='Ghana card / ID')),
                ('plot_number', models.CharField(blank=True, max_length=60, verbose_name='Plot no.')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Location / community')),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size')),
                ('size_unit', models.CharField(choices=[('ACRES', 'Acres'), ('PLOTS', 'Plots'), ('HECTARES', 'Hectares'), ('SQUARE_METRES', 'Square metres'), ('FEET', 'Feet')], default='ACRES', max_length=20, verbose_name='Unit')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total price')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Method of receipt')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Receipt no.')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'land record',
                'verbose_name_plural': 'land records',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
