"""
Django settings for the LandPro Records Management System.

Generated by 'django-admin startproject' using Django 6.1.1, then customized.

Environment variables are read from a `.env` file (see `.env.example`).
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (if present)
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    """Return a boolean value from an environment variable."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    """Return a comma separated environment variable as a list."""
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-cq^624i90*vtg%ru7+k9jr6r#t+ven3ylj&5mgl58bfb!l0uym",
)

DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")

# ---------------------------------------------------------------------------
# Hosting auto-configuration (Vercel zero-config Django)
# ---------------------------------------------------------------------------
# Vercel sets VERCEL=1 at build and runtime. When present we register the
# deployment domains as zero-config fallbacks so the site does not answer
# 400/404 because ALLOWED_HOSTS only lists localhost. Django's ALLOWED_HOSTS
# understands a leading "." as a suffix match (".vercel.app" covers every
# deployment domain), while CSRF_TRUSTED_ORIGINS needs exact origins, so we
# keep one concrete origin here and expect the real deployment domain (and any
# custom domain) to be added via DJANGO_ALLOWED_HOSTS /
# DJANGO_CSRF_TRUSTED_ORIGINS as described in DEPLOY.md. Explicit env vars
# always win: anything listed there is kept.
ON_VERCEL = os.getenv("VERCEL", "").strip() == "1"

if ON_VERCEL:
    # ".vercel.app" is a Django suffix match covering every deployment domain;
    # the concrete origins for signing in must come from
    # DJANGO_CSRF_TRUSTED_ORIGINS (see DEPLOY.md) because CSRF origins take
    # no wildcards.
    for _host in (".vercel.app", "localhost", "127.0.0.1"):
        if _host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_host)
    # Vercel's function filesystem is read-only outside /tmp and is rebuilt on
    # every deploy, so without DATABASE_URL the app can only boot against
    # throwaway storage. Point SQLite there so the site renders its pages
    # (including /login/) instead of crashing - real deployments must set
    # DATABASE_URL (PostgreSQL) because records saved under /tmp vanish on the
    # next deploy, as DEPLOY.md explains.
    if not os.getenv("DATABASE_URL", "").strip():
        os.environ["VERCEL_SQLITE_PATH"] = "/tmp/db.sqlite3"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'landpro.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.branding",
            ],
        },
    },
]

WSGI_APPLICATION = "landpro.wsgi.application"
# NOTE: no ASGI_APPLICATION here on purpose. When both are set, Vercel prefers
# ASGI, which 404s this WSGI project. landpro/asgi.py is kept only so Django
# tooling that probes for it does not crash at import time.


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# SQLite is used for development. Set DATABASE_URL (e.g. a PostgreSQL URL)
# for production deployments.

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
# Vercel's runtime filesystem is read-only outside /tmp; honour an explicit
# override (set above when ON_VERCEL with no DATABASE_URL).
VERCEL_SQLITE_PATH = os.getenv("VERCEL_SQLITE_PATH", "").strip()

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL, conn_max_age=600, conn_health_checks=True
        )
    }
elif VERCEL_SQLITE_PATH:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": VERCEL_SQLITE_PATH,
            "OPTIONS": {"timeout": 20},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {"timeout": 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "core:login"
LOGIN_REDIRECT_URL = "core:dashboard"
LOGOUT_REDIRECT_URL = "core:login"


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Africa/Accra")

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Non-manifest storage: on serverless hosts (Vercel) a missing or
        # stale staticfiles.json manifest turns every page into a 500
        # (FUNCTION_INVOCATION_FAILED). Compressed without manifest still
        # serves compressed assets via WhiteNoise, minus content hashing.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# ---------------------------------------------------------------------------
# Sessions, messages & uploads
# ---------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours
CSRF_COOKIE_SAMESITE = "Lax"

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# Maximum upload size for documents (10 MB)
MAX_UPLOAD_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
ALLOWED_DOCUMENT_EXTENSIONS = [
    "pdf", "jpg", "jpeg", "png", "gif", "webp",
    "doc", "docx", "xls", "xlsx", "csv", "txt", "dwg",
]


# ---------------------------------------------------------------------------
# Production security (enabled automatically when DEBUG is off)
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------------
# Business / branding settings
# ---------------------------------------------------------------------------
BUSINESS_NAME = os.getenv("BUSINESS_NAME", "ABI LAND")
BUSINESS_SHORT_NAME = os.getenv("BUSINESS_SHORT_NAME", "ABI LAND")
BUSINESS_TAGLINE = os.getenv("BUSINESS_TAGLINE", "Land Sales Records Management")
BUSINESS_PHONE = os.getenv("BUSINESS_PHONE", "+233 00 000 0000")
BUSINESS_EMAIL = os.getenv("BUSINESS_EMAIL", "info@landpro.example")
BUSINESS_ADDRESS = os.getenv("BUSINESS_ADDRESS", "Accra, Ghana")
CURRENCY_SYMBOL = os.getenv("CURRENCY_SYMBOL", "GHS")
